name: Build and Download

on:
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    
    - name: Prepare Release Package
      run: |
        mkdir -p release
        cp server/target/*.jar release/
        cp -r server/src/main/bin/* release/
        cp -r server/src/main/config/* release/
        cp README.md release/
        cd release && zip -r ../kkFileView-package.zip *
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kkFileView-package
        path: kkFileView-package.zip
        retention-days: 7
